# Minimal type stubs for py_dem_bones

from typing import Any, List, Dict, Tuple, Optional, Union, Callable

class DemBones:
    def __init__(self) -> None: ...
    def compute(self, vertices: Any, *args: Any, **kwargs: Any) -> Any: ...

class DemBonesExt:
    def __init__(self) -> None: ...
    def compute(self, vertices: Any, *args: Any, **kwargs: Any) -> Any: ...

class DemBonesWrapper:
    def __init__(self) -> None: ...
    def compute(self, vertices: Any, *args: Any, **kwargs: Any) -> Any: ...

class DemBonesExtWrapper:
    def __init__(self) -> None: ...
    def compute(self, vertices: Any, *args: Any, **kwargs: Any) -> Any: ...

class DCCInterface:
    def __init__(self) -> None: ...

class DemBonesError(Exception): ...
class ParameterError(DemBonesError): ...
class ComputationError(DemBonesError): ...
class IndexError(DemBonesError): ...
class NameError(DemBonesError): ...
class ConfigurationError(DemBonesError): ...
class NotImplementedError(DemBonesError): ...
class IOError(DemBonesError): ...

def numpy_to_eigen(array: Any) -> Any: ...
def eigen_to_numpy(matrix: Any) -> Any: ...
