[build-system]
requires = [
    "scikit-build-core>=0.5.0",
    "pybind11>=2.10.0",
    "numpy>=1.20.0",
    "setuptools>=42.0.0",
    "wheel>=0.36.0",
]
build-backend = "scikit_build_core.build"

[project]
name = "py-dem-bones"
version = "0.3.0"
description = "Python bindings for the Dem Bones library"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "BSD-3-Clause"}
authors = [
    {name = "Long Hao", email = "hal.long@outlook.com"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: C++",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Multimedia :: Graphics :: 3D Modeling",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "numpy>=1.20.0",
]

[project.optional-dependencies]
dev = [
    "nox>=2023.4.22",
]
docs = [
    "sphinx>=7.0.0",
    "furo>=2023.5.20",
    "sphinx-autobuild>=2021.3.14",
    "pybind11-stubgen>=0.16.0",
    "myst-parser>=2.0.0",
]
lint = [
    "black<23.3.0",
    "ruff<0.0.270",
    "isort<5.12.0",
    "autoflake>=2.0.0",
]
test = [
    "pytest>=7.3.1",
    "pytest-cov>=4.1.0",
]
build = [
    "build>=0.10.0",
    "twine>=4.0.2",
]

[project.urls]
Homepage = "https://github.com/loonghao/py-dem-bones"
Documentation = "https://py-dem-bones.readthedocs.io"
Issues = "https://github.com/loonghao/py-dem-bones/issues"
Changelog = "https://github.com/loonghao/py-dem-bones/blob/main/CHANGELOG.md"

[tool.scikit-build]
wheel.packages = ["src/py_dem_bones"]
wheel.expand-macos-universal-tags = true
wheel.py-api = "cp37"
wheel.platlib = true  # 确保使用标准的平台标签
sdist.include = ["src/py_dem_bones/*.py", "src/py_dem_bones/*.pyi", "CMakeLists.txt", "extern/CMakeLists.txt"]
sdist.exclude = ["extern/eigen/unsupported", "extern/eigen/bench", "extern/eigen/test", "extern/eigen/demos"]
cmake.version = ">=3.15"  # 添加版本比较符号
cmake.build-type = "Release"
build.verbose = true
cmake.args = ["-DCMAKE_POSITION_INDEPENDENT_CODE=ON"]

[tool.scikit-build.cmake.define]
PY_DEM_BONES_BUILD_TESTS = "OFF"
PY_DEM_BONES_BUILD_EXAMPLES = "OFF"

[tool.cibuildwheel]
build-verbosity = 3

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.3.0"
tag-format = "v$version"
version-files = [
    "pyproject.toml:version",
    "src/py_dem_bones/__version__.py",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"

[tool.ruff]
line-length = 120
target-version = "py37"
# Ignore extern directory and generated stub files
exclude = ["extern", "**/*.pyi"]
src = ["src", "nox_actions", "noxfile.py"]
select = ["E", "F", "W", "I"]
ignore = ["W293"]  # Ignore whitespace warnings in blank lines

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"noxfile.py" = ["E402"]
"docs/conf.py" = ["E402", "F401"]

[tool.isort]
profile = "black"
line_length = 120
skip = ["extern"]
skip_glob = ["*.pyi"]
