# py-dem-bones: Python bindings for the Dem Bones library
# This project uses scikit-build-core to build C++ extensions and Poetry for dependency management

[build-system]
# Build system dependencies
requires = [
    "scikit-build-core>=0.5.0",  # For building C++ extensions
    "pybind11>=2.10.0",          # For Python/C++ bindings
    "numpy>=1.20.0",             # Numerical computation library
    "setuptools>=42.0.0",        # Installation tools
    "wheel>=0.36.0",             # Wheel packaging tool
    "poetry-core>=1.0.0",        # Poetry core functionality
]
build-backend = "scikit_build_core.build"  # Use scikit-build-core as the build backend

# PEP 621 project metadata for scikit-build-core
[project]
name = "py-dem-bones"
version = "0.6.5"
description = "Python bindings for the Dem Bones library"
readme = "README.md"
license = {text = "BSD-3-Clause"}
authors = [
    {name = "Long Hao", email = "hal.long@outlook.com"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: C++",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Multimedia :: Graphics :: 3D Modeling",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
# Support Python 3.7 and above
requires-python = ">=3.7"
dependencies = [
    "numpy>=1.20.0",  # Numerical computation library
]

# Project related links
[project.urls]
repository = "https://github.com/loonghao/py-dem-bones"
homepage = "https://github.com/loonghao/py-dem-bones"
documentation = "https://loonghao.github.io/py-dem-bones"
changelog = "https://github.com/loonghao/py-dem-bones/blob/main/CHANGELOG.md"
issues = "https://github.com/loonghao/py-dem-bones/issues"

# Poetry configuration (for dependency management)
[tool.poetry]
name = "py-dem-bones"
version = "0.6.5"
description = "Python bindings for the Dem Bones library"
readme = "README.md"
license = "BSD-3-Clause"
authors = [
    "Long Hao <hal.long@outlook.com>",
]
packages = [{include = "py_dem_bones", from = "src"}]  # Specify package path
keywords = ["animation", "skinning", "rigging", "computer graphics", "3d"]
include = ["LICENSE.md", "README.md", "CHANGELOG.md"]
exclude = ["extern/dem-bones/test/**/*"]

# Poetry URL configuration
[tool.poetry.urls]
changelog = "https://github.com/loonghao/py-dem-bones/blob/main/CHANGELOG.md"
issues = "https://github.com/loonghao/py-dem-bones/issues"

# Poetry dependency configuration
[tool.poetry.dependencies]
python = ">=3.7"  # Support Python 3.7 and above
numpy = ">=1.20.0"  # Numerical computation library

# Test dependencies (optional)
[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = ">=6.0.0"  # Testing framework
pytest-cov = ">=2.12.0"  # Test coverage tool

# scikit-build configuration
[tool.scikit-build]
wheel.packages = ["src/py_dem_bones"]  # Specify packaging path
wheel.exclude = ["tests/*"]  # Exclude test files
wheel.expand-macos-universal-tags = true  # Support macOS universal binaries
# Files to include in the source distribution
sdist.include = ["src/py_dem_bones/*", "src/binding/*", "CMakeLists.txt", "LICENSE.md", "README.md", "extern/dem-bones/*", "extern/eigen/*"]
sdist.exclude = ["tests/data/*"]  # Exclude test data

# CMake configuration
[tool.scikit-build.cmake]
version = ">=3.15"  # Require CMake 3.15 or above
build-type = "Release"  # Build type is Release

# CMake definitions
[tool.scikit-build.cmake.define]
# Do not use Python stable ABI as pybind11 is not compatible with it
PYTHON_LIMITED_API = "OFF"  # Disable Python stable ABI

# Commitizen configuration (for version management and commit conventions)
[tool.commitizen]
name = "cz_conventional_commits"  # Use conventional commit format
version = "0.6.6"  # Current version
tag_format = "$version"  # Tag format without 'v' prefix
version_files = [  # Files to update version in
    "pyproject.toml:version",
    "src/py_dem_bones/__version__.py:__version__",
    "docs/conf.py:release",
    "docs/conf.py:version",
    ".github/CITATION.cff:version",
]

# Pytest configuration
[tool.pytest.ini_options]
testpaths = ["tests"]  # Test file paths
python_files = "test_*.py"  # Test file naming convention
python_classes = "Test*"  # Test class naming convention
python_functions = "test_*"  # Test function naming convention
addopts = "--cov=py_dem_bones --cov-report=term-missing --cov-report=xml:coverage.xml"  # Test parameters

# isort configuration
[tool.isort]
profile = "black"  # Compatible with black formatter
multi_line_output = 3  # Vertical hanging indent
include_trailing_comma = true  # Include trailing comma in multi-line imports
force_grid_wrap = 0  # Don't force grid wrap
use_parentheses = true  # Use parentheses for imports
ensure_newline_before_comments = true  # Ensure newline before comments
line_length = 88  # Same as black's default line length
known_first_party = ["py_dem_bones"]  # Treat py_dem_bones as first party
known_third_party = ["numpy", "pybind11", "pytest"]  # Known third party imports
skip = ["extern", "*.pyi"]  # Skip extern directory and .pyi files
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]  # Import sections order

# ruff configuration
[tool.ruff]
line-length = 88  # Same as black's default line length
target-version = "py37"  # Target Python 3.7
select = ["E", "F", "W"]  # Error, Flake8, Warning
# 忽略一些特定问题
ignore = [
    "E501",  # Line too long (handled by black)
    "F821",  # Undefined name (issues with type stubs)
]

# Exclude files and directories
exclude = [
    ".git",
    ".github",
    "__pycache__",
    "build",
    "dist",
    "extern",
    "venv",
    ".venv",
    "*.egg-info",
    "*.pyi",  # Exclude type stub files
]

# black configuration
[tool.black]
line-length = 88  # Default line length
target-version = ["py37", "py38", "py39", "py310", "py311"]  # Target Python versions
include = '\.pyi?$'  # Include Python files and type stubs
exclude = '''(
    /(\.
      | \.git
      | \.github
      | __pycache__
      | build
      | dist
      | extern
      | venv
      | \.venv
      | .*\.egg-info
    )/
)'''  # Exclude patterns
