"""
Template for version.py file generated by setuptools_scm.
This template ensures that __dem_bones_version__ is included in the generated file.
"""

__all__ = ["__version__", "__version_tuple__", "version", "version_tuple", "__dem_bones_version__"]

TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple
    from typing import Union

    VERSION_TUPLE = Tuple[Union[int, str], ...]
else:
    VERSION_TUPLE = object

version: str
__version__: str
__dem_bones_version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = '{version}'
__dem_bones_version__ = "v1.2.1-2-g09b899b"  # Hardcoded Dem Bones library version
__version_tuple__ = version_tuple = {version_tuple}
