name: 'Setup ccache'
description: 'Sets up ccache for faster builds'

inputs:
  platform:
    description: 'Platform (Linux, Windows, macOS-Intel, macOS-ARM)'
    required: true
    default: 'Linux'
  python:
    description: 'Python version (cp38, cp39, etc.)'
    required: true
    default: 'cp310'
  max-size:
    description: 'Maximum size of ccache'
    required: false
    default: '2G'

runs:
  using: "composite"
  steps:
    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ inputs.platform }}-ccache-${{ inputs.python }}
        max-size: ${{ inputs.max-size }}
