name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
      
      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@0.24.0
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: main
          version_files: |
            pyproject.toml:version
            src/py_dem_bones/__version__.py
            docs/conf.py:release
            docs/conf.py:version
            .github/CITATION.cff:version
      
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
