name: Documentation

on:
  push:
    branches: [main]
    tags: ['*']
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox build "sphinx>=7.0.0,<9.0.0" sphinx_rtd_theme>=1.3.0 myst-parser sphinxcontrib-googleanalytics pillow linkify-it-py
          python -m pip install -e .

      - name: Build documentation
        run: |
          python -m nox -s docs

      - name: Create GitHub Pages structure for latest docs
        run: |
          # 确保脚本是可执行的
          chmod +x .github/scripts/create_gh_pages_structure.sh
          
          # 执行脚本创建 GitHub Pages 结构并复制文档
          bash .github/scripts/create_gh_pages_structure.sh "docs/_build/html"

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages-root
          keep_files: true
          user_name: 'github-actions'
          user_email: 'github-actions@github.com'
          commit_message: 'docs: update documentation'
