python-matrix: &python-matrix
  python: [cp38, cp39, cp310, cp311, cp312]
  include:
    - python: cp38
      python-version: '3.8'
    - python: cp39
      python-version: '3.9'
    - python: cp310
      python-version: '3.10'
    - python: cp311
      python-version: '3.11'
    - python: cp312
      python-version: '3.12'

python-matrix-arm: &python-matrix-arm
  python: [cp39, cp310, cp311, cp312]
  include:
    - python: cp39
      python-version: '3.9'
    - python: cp310
      python-version: '3.10'
    - python: cp311
      python-version: '3.11'
    - python: cp312
      python-version: '3.12'
